### PR TITLE
Create INT-D_NE-Atlantic.csv

### PR DESCRIPTION
**Pull request by Dirk--**
some test data

### CODE REVIEW

**Comment by malcolmh** [comment]
Dirk,

OK except that the semicolons should be replaced with commas.
Would you please make that change & re-submit?

Malcolm

**Comment by Dirk--** [comment]
Still do not understand the github csv renderer fully: I do have cells with commas like in this line
1700;GB;2565;English Channel, Saint Agnes Head to Dodman Point including the Isles of Scilly;49°22.89’N;....
Shall I use Quotation marks for text cells like this "English Channel, Saint Agnes Head to Dodman Point including the Isles of Scilly"?

**Comment by malcolmh** [comment]
On 26 Jan 2015, at 20:04, Dirk-- notifications@github.com wrote:

> Still do not understand the github csv renderer fully:

Nor do I. Aun should be able to advise you as he did this successfully.

**Comment by Dirk--** [comment]
Aun picked an rather easy example ;-)
I will do some trial and error tomorrow to practise my limited github skills...

**Comment by Skippern** [comment]
Strings with separator character (comma in this case) need to be surrounded by quotes

`1700,GB,2565,"English Channel, Saint Agnes Head to Dodman Point including the Isles of Scilly",49°22.89’N,....` would be right.

You can try opening the cvs in a spreadsheet app, such as Excel or OpenOffice.org. I used OpenOffice.org as assistance for my test file, afterwords tested it in Excel, and noticed Excel doesn't support non-ansi characters (i.e. no accents, no special characters such as ç, å, ø, etc.).

If you are unsure about syntax, I recommend to edit with OpenOffice.org

OpenOffice.org also helped me convert Lat/Long to **dd.dddd** format by entering into the cell `=-(dd+(mm.m/60))` - Almost all my positions are **S** and **W**, for **N** and **E** you can drop the _-_

**Comment by Skippern** [comment]
**csv** is actually quite simple, both in writing and in parsing, you just need to count and be strict on separator sign, if you by any chance need separator sign inside a cell, then just quote it.

**Comment by Dirk--** [comment]
Aun:
yes, openoffice is my friend, too.
Special thanks for the Lat/Long convert hint!
Hoped the github csv renderer would accept a semicolon (my favorite delimiter), too....

This might make your life easier: pdf2excel converter 'Nitro Pro 9' works verry well on these files! (WIN, 30days trial)

**Comment by malcolmh** [comment]
On 26 Jan 2015, at 20:28, Dirk-- notifications@github.com wrote:

> Hoped the github csv renderer would accept a semicolon

Except many tools that use CSV files tend to expect commas, as is implied with the acronym CSV=“Comma Separated Variables"=

**Comment by Skippern** [comment]
Actually now I am looking for a simple **BSB/KAP** viewer to view single .KAP files, I have made a fork where I am trying to make the Brazilian national catalogue in the same **CSV** format, though their catalogue didn't provide max/min lat/long, scale and scale-latitude, since I have most of them as BSB/KAP I thought I can extract that information from them. I am not very keen on converting them to GeoTIFF with `libbsb` though.

**Pull request merged**
